name: Docker

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "Dockerfile"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout pleroma repository
        run: git clone -b develop https://git.pleroma.social/pleroma/pleroma pleroma
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Get latest git commit
        run: echo "LAST_COMMIT=$(git log -1 --pretty=%h)" >> $GITHUB_ENV
        working-directory: pleroma
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: pleroma
          push: true
          build-args: |
            BUILD_DATE: ${{ env.CURRENT_DATE }}
            VCS_REF: ${{ env.LAST_COMMIT }}
          tags: |
            ghcr.io/mirror-kt/pleroma:latest
            ghcr.io/mirror-kt/pleroma:${{ env.LAST_COMMIT }}
